#!/usr/bin/env bun
// Generates src/registry-preview.tsx from registry/ so the preview site
// always mirrors what is in the registry without manual editing.
//
// For every registry block the preview renders the first renderable
// component (skipping async server components, which need an RSC host)
// and embeds the source code of the block's files plus any local
// registry:ui dependencies, shown beneath the demo.
//
// Usage: bun scripts/generate-preview-index.ts [--watch]

import { readFileSync, writeFileSync, watch } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const registryJsonPath = path.join(root, "registry.json");
const outPath = path.join(root, "src", "registry-preview.tsx");

const toPascal = (name: string) =>
  name
    .split(/[-_.]/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");

const toImportPath = (relPath: string) => `@/${relPath.replace(/\.tsx$/, "")}`;

const SOURCE_EXTENSIONS = new Set([".ts", ".tsx", ".css"]);

// Async server components cannot run in the client-side preview.
const SERVER_COMPONENT = /export default async|"use server"/;

interface RegistryFile {
  path: string;
  type: string;
}
interface RegistryItem {
  name: string;
  type: string;
  title: string;
  description?: string;
  registryDependencies?: string[];
  files: RegistryFile[];
}
interface PreviewFile {
  path: string;
  source: string;
}

function readSourceFiles(item: RegistryItem): PreviewFile[] {
  return item.files
    .filter((file) => SOURCE_EXTENSIONS.has(path.extname(file.path)))
    .map((file) => ({
      path: file.path,
      source: readFileSync(path.join(root, file.path), "utf8"),
    }));
}

function readRegistry(): { items: RegistryItem[] } {
  try {
    return JSON.parse(readFileSync(registryJsonPath, "utf8")) as {
      items: RegistryItem[];
    };
  } catch (error) {
    throw new Error(
      `[preview-gen] Failed to parse ${registryJsonPath}: ${(error as Error).message}`,
    );
  }
}

function generate() {
  const { items } = readRegistry();

  // Local ui primitives that blocks can depend on (by item name).
  const localUiItems = new Map(
    items
      .filter((item) => item.type === "registry:ui")
      .map((item) => [item.name, item]),
  );

  const imports: string[] = [];
  const blockEntries: string[] = [];
  const skipped: string[] = [];

  for (const item of items) {
    // Only blocks/components are previewable; lib and hook items exist as
    // dependencies of other items and have no renderable demo.
    if (
      item.type === "registry:ui" ||
      item.type === "registry:lib" ||
      item.type === "registry:hook"
    )
      continue;

    const candidates = item.files.filter(
      (file) =>
        file.type === "registry:component" && file.path.endsWith(".tsx"),
    );

    // Demo with the first renderable component: the block's entry file,
    // or — if that is an async server component — any other client
    // component shipped with the block.
    let entry: RegistryFile | undefined;
    let entryStem = "";
    for (const candidate of candidates) {
      if (
        SERVER_COMPONENT.test(
          readFileSync(path.join(root, candidate.path), "utf8"),
        )
      ) {
        skipped.push(`${candidate.path} (async server component)`);
        continue;
      }
      entry = candidate;
      entryStem = toPascal(path.basename(candidate.path, ".tsx"));
      break;
    }

    // Source shown beneath the demo: the block's own files plus the files
    // of any local registry:ui dependencies it uses.
    const files: PreviewFile[] = readSourceFiles(item);
    for (const dependency of item.registryDependencies ?? []) {
      const localItem = localUiItems.get(dependency);
      if (localItem) files.push(...readSourceFiles(localItem));
    }

    if (!entry) {
      blockEntries.push(
        `  { name: ${JSON.stringify(item.name)}, title: ${JSON.stringify(item.title)}, description: ${JSON.stringify(item.description ?? "")}, files: ${JSON.stringify(files)}, Component: null },`,
      );
      skipped.push(`${item.name} (no renderable .tsx file)`);
      continue;
    }

    const varName = toPascal(item.name);
    imports.push(
      `import * as ${varName}Module from "${toImportPath(entry.path)}";`,
    );
    blockEntries.push(
      `  { name: ${JSON.stringify(item.name)}, title: ${JSON.stringify(item.title)}, description: ${JSON.stringify(item.description ?? "")}, files: ${JSON.stringify(files)}, Component: resolveExport(${varName}Module, ${JSON.stringify(entryStem)}) },`,
    );
  }

  const output = `// AUTO-GENERATED by scripts/generate-preview-index.ts — do not edit.
/* eslint-disable */

import type { ComponentType } from "react";

${imports.join("\n")}

export type PreviewFile = {
  path: string;
  source: string;
};

export type BlockDemo = {
  name: string;
  title: string;
  description: string;
  files: PreviewFile[];
  Component: ComponentType | null;
};

function resolveExport(
  moduleNamespace: Record<string, unknown>,
  name: string,
): ComponentType | null {
  const candidate = moduleNamespace[name] ?? moduleNamespace.default;
  if (candidate == null) return null;
  return candidate as ComponentType;
}

export const blockDemos: BlockDemo[] = [
${blockEntries.join("\n")}
];
`;

  writeFileSync(outPath, output);
  console.log(
    `[preview-gen] ${blockEntries.length} blocks` +
      (skipped.length ? ` (skipped: ${skipped.join(", ")})` : ""),
  );
}

function debounce(fn: () => void, ms: number) {
  let timer: ReturnType<typeof setTimeout> | undefined;
  return () => {
    clearTimeout(timer);
    timer = setTimeout(fn, ms);
  };
}

generate();

if (process.argv.includes("--watch")) {
  const regen = debounce(() => {
    try {
      generate();
    } catch (error) {
      console.error("[preview-gen] regeneration failed:", error);
    }
  }, 100);
  watch(path.join(root, "registry"), { recursive: true }, regen);
  watch(registryJsonPath, regen);
  console.log("[preview-gen] watching registry/ for changes…");
}
