#!/usr/bin/env bun
// Generates preview/registry-preview.tsx from examples/ so the preview site
// always mirrors what is in the examples folders without manual editing.
//
// Every examples/<area>/<name>.tsx becomes one preview entry, grouped by
// area. Each entry is rendered from its default export or the PascalCase
// named export matching the file name, and its full source is shown beneath
// the demo. An optional `export const description = "…"` provides the
// entry's description.
//
// Usage: bun scripts/generate-preview-index.ts [--watch]

import {
  existsSync,
  readdirSync,
  readFileSync,
  watch,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const examplesDir = path.join(root, "examples");
const outPath = path.join(root, "preview", "registry-preview.tsx");

// Preferred tab order; unknown area folders follow alphabetically.
const AREA_ORDER = ["workspace", "quiz", "plot", "code"];

const toPascal = (name: string) =>
  name
    .split(/[-_.]/)
    .flatMap((part) => (part ? [part[0].toUpperCase() + part.slice(1)] : []))
    .join("");

const toImportPath = (relPath: string) => `@/${relPath.replace(/\.tsx$/, "")}`;

// Async server components cannot run in the client-side preview.
const SERVER_COMPONENT = /export default async|"use server"/;
const DESCRIPTION = /export const description = "((?:[^"\\]|\\.)*)";/;
const DEFAULT_EXPORT = /export default (?!async)/;
const NAMED_EXPORT = (name: string) =>
  new RegExp(`export (async )?(function|const) ${name}\\b`);

interface PreviewFile {
  path: string;
  source: string;
}
interface PreviewEntry {
  name: string;
  area: string;
  title: string;
  description: string;
  files: PreviewFile[];
  componentName: string | null;
  importPath: string;
}

function listAreas(): string[] {
  if (!existsSync(examplesDir)) return [];
  const dirs = readdirSync(examplesDir, { withFileTypes: true }).flatMap(
    (entry) => (entry.isDirectory() ? [entry.name] : []),
  );
  const known = AREA_ORDER.filter((area) => dirs.includes(area));
  const extra = dirs
    .filter((dir) => !AREA_ORDER.includes(dir))
    .sort((a, b) => a.localeCompare(b));
  return [...known, ...extra];
}

function collectEntries(): PreviewEntry[] {
  const entries: PreviewEntry[] = [];

  for (const area of listAreas()) {
    const dir = path.join(examplesDir, area);
    const files = readdirSync(dir)
      .filter((file) => file.endsWith(".tsx"))
      .sort((a, b) => a.localeCompare(b));

    for (const file of files) {
      const relPath = `examples/${area}/${file}`;
      const stem = path.basename(file, ".tsx");
      const source = readFileSync(path.join(root, relPath), "utf8");

      if (SERVER_COMPONENT.test(source)) {
        console.error(
          `[preview-gen] skipped ${relPath} (async server component)`,
        );
        continue;
      }

      const componentName = toPascal(stem);
      const renderable =
        DEFAULT_EXPORT.test(source) || NAMED_EXPORT(componentName).test(source);
      const description =
        source.match(DESCRIPTION)?.[1]?.replace(/\\"/g, '"') ?? "";

      entries.push({
        name: stem,
        area,
        title: toPascal(stem).replace(/([a-z0-9])([A-Z])/g, "$1 $2"),
        description,
        files: [{ path: relPath, source }],
        componentName: renderable ? componentName : null,
        importPath: toImportPath(relPath),
      });
    }
  }

  return entries;
}

function generate() {
  const entries = collectEntries();

  const imports: string[] = [];
  const usedModuleNames = new Set<string>();
  const skipped: string[] = [];
  const blockEntries: string[] = [];

  for (const entry of entries) {
    if (!entry.componentName) {
      skipped.push(
        `${entry.files[0]?.path} (no default or ${entry.componentName ?? "matching"} export)`,
      );
      continue;
    }

    let moduleName = toPascal(entry.name);
    if (usedModuleNames.has(moduleName)) {
      moduleName = toPascal(`${entry.area}-${entry.name}`);
    }
    if (usedModuleNames.has(moduleName)) {
      throw new Error(`[preview-gen] duplicate module name: ${moduleName}`);
    }
    usedModuleNames.add(moduleName);

    imports.push(`import * as ${moduleName}Module from "${entry.importPath}";`);
    blockEntries.push(
      `  { name: ${JSON.stringify(entry.name)}, area: ${JSON.stringify(entry.area)}, title: ${JSON.stringify(entry.title)}, description: ${JSON.stringify(entry.description)}, files: ${JSON.stringify(entry.files)}, Component: resolveExport(${moduleName}Module, ${JSON.stringify(entry.componentName)}) },`,
    );
  }

  const output = `// AUTO-GENERATED by scripts/generate-preview-index.ts — do not edit.

import type { ComponentType } from "react";

${imports.join("\n")}

export type PreviewFile = {
  path: string;
  source: string;
};

export type BlockDemo = {
  name: string;
  area: string;
  title: string;
  description: string;
  files: PreviewFile[];
  Component: ComponentType | null;
};

function resolveExport(
  moduleNamespace: Record<string, unknown>,
  name: string,
): ComponentType | null {
  const candidate = moduleNamespace[name] ?? moduleNamespace.default;
  if (candidate == null) return null;
  return candidate as ComponentType;
}

export const blockDemos: BlockDemo[] = [
${blockEntries.join("\n")}
];
`;

  writeFileSync(outPath, output);
  process.stdout.write(
    `[preview-gen] ${blockEntries.length} blocks` +
      (skipped.length ? ` (skipped: ${skipped.join(", ")})` : "") +
      "\n",
  );
}

function debounce(fn: () => void, ms: number) {
  let timer: ReturnType<typeof setTimeout> | undefined;
  return () => {
    clearTimeout(timer);
    timer = setTimeout(fn, ms);
  };
}

generate();

if (process.argv.includes("--watch")) {
  const regen = debounce(() => {
    try {
      generate();
    } catch (error) {
      console.error("[preview-gen] regeneration failed:", error);
    }
  }, 100);
  watch(examplesDir, { recursive: true }, regen);
  process.stdout.write("[preview-gen] watching examples/ for changes…\n");
}
