import { mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const entrypoint = resolve(
  projectRoot,
  'registry/calculator/lib/solver/solver.worker.ts',
)
const outputPath = resolve(
  projectRoot,
  'registry/calculator/lib/generated/solver-worker-source.ts',
)
const build = await Bun.build({
  entrypoints: [entrypoint],
  target: 'browser',
  format: 'esm',
  minify: true,
  sourcemap: 'none',
})

if (!build.success || build.outputs.length !== 1) {
  throw new Error('The solver worker could not be bundled.')
}

const source = await build.outputs[0].text()
mkdirSync(dirname(outputPath), { recursive: true })
await Bun.write(
  outputPath,
  `// Generated by scripts/render-calculator-solver-worker.ts.\nexport const SOLVER_WORKER_SOURCE = ${JSON.stringify(source)}\n`,
)
