import { mkdirSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export function renderHelpMarkdown(markdown: string): string {
  return Bun.markdown.html(markdown, {
    tagFilter: true,
    noHtmlBlocks: true,
    noHtmlSpans: true,
  })
}

if (import.meta.main) {
  const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
  const markdown = readFileSync(
    resolve(projectRoot, 'registry/calculator/lib/help.md'),
    'utf8',
  )
  const html = renderHelpMarkdown(markdown)
  const moduleSource = `// Generated by scripts/render-calculator-help.ts with Bun.markdown.\nexport const HELP_CONTENT_HTML = ${JSON.stringify(html)}\n`
  const outputPath = resolve(
    projectRoot,
    'registry/calculator/lib/generated/help-content.ts',
  )

  mkdirSync(dirname(outputPath), { recursive: true })
  await Bun.write(outputPath, moduleSource)
}
